name: C CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile the program
        run: gcc -o my_program main.c

      - name: Run the tests
        run: ./my_program